server:
  port: 8801
spring:
  application:
    name: kafka-streams-aggregate-sample
  cloud:
    stream:
      bindings:
        aggregate-in-0:
          destination: kafka-stream
  stream:
    kafka:
      streams:
        binder:
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            commit.interval.ms: 1000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
  instance:
    instance-id: stream-provider-8801
    prefer-ip-address: true #访问路径可以显示IP地址