server:
  port: 9527

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/common-service/**
#            - After=2020-03-15T15:35:07.412+08:00[GMT+08:00]
#            - Cookie=name,zh1991
            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username, \d+ #要有参数名username并且值还要啥整数才能路由
          filters:
            - StripPrefix=1
eureka:
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka