server:
  port: 9528

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: common-service
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/payment/get/**
eureka:
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka